version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile-node
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development