FROM node:16.14-alpine3.14
RUN apk update

# Create app directory
RUN mkdir /app
WORKDIR /app

# Install dependencies
COPY package*.json .
RUN npm install
RUN npm install webpack-dev-server --save-dev

# Exports
EXPOSE 3000

# CMD [ "npm", "run", "test" ]
CMD ["npm", "start"]