FROM node:16.14-alpine3.14
RUN apk update

# Create app directory
RUN mkdir /app
WORKDIR /app

# Install dependencies
COPY package*.json .
RUN npm install

# Exports
EXPOSE 3000

CMD [ "npm", "start" ]